---
title: "Typst は刺さらなかった話"
date: "2025-10-10"
categories: [Tech, Writing]
description: "新しい組版「typst」はまだいいかな…"
---

私は普段、簡単ドキュメントは Google Docs で、レポートや報告書等は LaTeX を使って書いています。
ただ、LaTeX ってとても面倒なんですよね。
インストールも複雑で時間が掛かるし、設定ファイルや中間生成物が大量に溜まっていきます。
エラーもよくわからないし、環境依存で失敗することもあるし…。
特に困るのは、PC の環境をクリーンにして「0の状態から LaTeX で文書がコンパイルできるような状態にする」までが大変なことです。
下手したら、セットアップで1日を消費してしまいます。
(もちろん、Docker などで対応可能なのですが、手を出せていません)。

そんな中、2023 年くらいに「Typst」という新しい組版システムが登場しました。
一応、布教系の記事もいくつか挙げておきます。

- [「Typst： いい感じのLaTeXの代替」(大阪大学 山口先生の Website より)](https://www-het.phys.sci.osaka-u.ac.jp/~yamaguch/j/typst.html)
- [「Typstのここがすごい！！」(Qiita の記事)](https://qiita.com/hikoharu14142/items/aa8cfb70d079b0324fba)


新しいもの好きの私も、実際に1年くらい使ってみました。
しかし、タイトルにもあるように、Typst は私には刺さりませんでした。
この記事では、Typst を使ってみて、よいと感じた点も悪いと感じた点も説明し、「また LaTeX でいいや…」に至った理由を綴ります。
なんかブログっぽくていいね！


## Typst のここがすごい
### コンパイルが早い
LaTeX から移行した人々は、まずここに驚くはずです。
コンパイルとは、書かれたコードを実際に文書に変換する過程のことです。
LaTeX だと (文書の内容や量にもよりますが) 1回のコンパイルに1分くらいかかる印象です。
文章の内容を変更してから反映させるのに1分。
普段 Word や Google Docs (内容の変更 ＝ 完成品の更新) を使っている人からすれば、信じられないと思うかもしれません。

その点、Typst はコンパイルが爆速で、リアルタイムプレビューができてしまう点は驚きました。
VS Code の左画面で文章を書いたら、右の整った文書の内容も変わっていく。
もちろん、数式もその場でコンパイルされていたのが素晴らしかったです。

コンパイルの速さ (というかリアルタイムプレビュー) は、LaTeX に戻る私を引き止める最大の要因だったと思います。なにより書いていて気持ちがよいのです。
ただ、これは「すっぱい葡萄」かもしれませんが、いざ LaTeX に戻ってくると、別にリアルタイムプレビューはなくてもよい気がします。
たしかに、数式や図表が正しく出力されているかを確認したい場合は、確認のたびに一々コンパイルするのは面倒だと感じます。
全体の執筆時間と比較して、そして他の不利益も勘案すれば、妥協せざるを得ない部分だったと感じました。



## Typst のここがもう少し
「機能としては存在しているがリサーチ不足で見つけられていないだけ」というのは除外します。
新しいものを学ぶ際には、それなりの学習コストを支払うことを許容しなければなりません。

### パッケージが少なすぎる
やはり新興の組版システムということもあり、パッケージやテンプレートが整っていない印象です。
自然科学系分野のためのパッケージはわかりませんが、少なくとも人文・社会科学向けのパッケージはあまりありません。
特に、私が Typst から手を引く決定的な原因になったのは、ゲーム理論のツリーを描くパッケージがなかったということです。
もちろん、他のツールで作成したり画像を描画したりして貼り付ければいいのですが、パッケージが一切なかったというのが衝撃的でした。
今後、世界の誰かが作るのだろうと思いますが、少なくとも現時点で、ゲームのツリーを Typst 内で描画したい人は諦めるしかありません。

また、引用の方法も人文・社会科学でよく使われる方法に対応していなかった印象です。
そもそも引用方法に関するパッケージも発展途上だと思いますが、APA や MLA などスタイルで参考文献リストを出力できなかったのは残念でした。
また、最終手段である手入力の (thebibliography) 環境すらありません。
CSL ファイルを使うと幾分かましになるのですが、流石に自由度が低く、躓く頻度が高かったように感じます。

### PDF を図として取り込めない
これはいずれアップデートされそうですが、現時点で PDF で作成された図を Typst で呼び出すことはできません。
普段のワークフローにもよるでしょうが、私にとってはだいぶ面倒でした。

## 結論
結論として、**卒論・レポートなどの論文執筆**には Typst はまだ使えないと思います。
簡単な文書なら Docs でよい、数式を含む長い文書なら LaTeX でよい。
乗り換えてより幸せになる、というほどの土俵にはまだ立っていないと思います。

一方、数式を含む短めの文章 (授業ノートとか) を作る際には、便利だと思います。
数式の書き方もかなり明快で、なによりも即時コンパイルが素晴らしすぎます。
結局、目的に応じて使うツールも選択するべきだということでした。